/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as EtfsRouteImport } from './routes/etfs'
import { Route as ExportDeskRouteImport } from './routes/export-desk'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as UsLinkRouteImport } from './routes/us-link'
import { Route as UsResearchRouteImport } from './routes/us-research'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiMarketStreamRouteImport } from './routes/api.market-stream'
import { Route as EtfsIndexRouteImport } from './routes/etfs.index'
import { Route as EtfsCodeRouteImport } from './routes/etfs.$code'
import { Route as IndustrySectorIdRouteImport } from './routes/industry.$sectorId'
import { Route as StatusSourcesRouteImport } from './routes/status.sources'
import { Route as StockTickerRouteImport } from './routes/stock.$ticker'
import { Route as UsResearchIndexRouteImport } from './routes/us-research.index'
import { Route as UsResearchReportIdRouteImport } from './routes/us-research.$reportId'
import { Route as UsSymbolRouteImport } from './routes/us.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfsRoute = EtfsRouteImport.update({
  id: '/etfs',
  path: '/etfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportDeskRoute = ExportDeskRouteImport.update({
  id: '/export-desk',
  path: '/export-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const UsLinkRoute = UsLinkRouteImport.update({
  id: '/us-link',
  path: '/us-link',
  getParentRoute: () => rootRouteImport,
} as any)
const UsResearchRoute = UsResearchRouteImport.update({
  id: '/us-research',
  path: '/us-research',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketStreamRoute = ApiMarketStreamRouteImport.update({
  id: '/api/market-stream',
  path: '/api/market-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfsIndexRoute = EtfsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EtfsRoute,
} as any)
const EtfsCodeRoute = EtfsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => EtfsRoute,
} as any)
const IndustrySectorIdRoute = IndustrySectorIdRouteImport.update({
  id: '/industry/$sectorId',
  path: '/industry/$sectorId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSourcesRoute = StatusSourcesRouteImport.update({
  id: '/status/sources',
  path: '/status/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTickerRoute = StockTickerRouteImport.update({
  id: '/stock/$ticker',
  path: '/stock/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const UsResearchIndexRoute = UsResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsResearchRoute,
} as any)
const UsResearchReportIdRoute = UsResearchReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => UsResearchRoute,
} as any)
const UsSymbolRoute = UsSymbolRouteImport.update({
  id: '/us/$symbol',
  path: '/us/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclosures': typeof DisclosuresRoute
  '/etfs': typeof EtfsRouteWithChildren
  '/export-desk': typeof ExportDeskRoute
  '/research': typeof ResearchRoute
  '/us-link': typeof UsLinkRoute
  '/us-research': typeof UsResearchRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/api/market-stream': typeof ApiMarketStreamRoute
  '/etfs/$code': typeof EtfsCodeRoute
  '/industry/$sectorId': typeof IndustrySectorIdRoute
  '/status/sources': typeof StatusSourcesRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/us-research/$reportId': typeof UsResearchReportIdRoute
  '/us/$symbol': typeof UsSymbolRoute
  '/etfs/': typeof EtfsIndexRoute
  '/us-research/': typeof UsResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclosures': typeof DisclosuresRoute
  '/export-desk': typeof ExportDeskRoute
  '/research': typeof ResearchRoute
  '/us-link': typeof UsLinkRoute
  '/watchlist': typeof WatchlistRoute
  '/api/market-stream': typeof ApiMarketStreamRoute
  '/etfs/$code': typeof EtfsCodeRoute
  '/industry/$sectorId': typeof IndustrySectorIdRoute
  '/status/sources': typeof StatusSourcesRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/us-research/$reportId': typeof UsResearchReportIdRoute
  '/us/$symbol': typeof UsSymbolRoute
  '/etfs': typeof EtfsIndexRoute
  '/us-research': typeof UsResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclosures': typeof DisclosuresRoute
  '/etfs': typeof EtfsRouteWithChildren
  '/export-desk': typeof ExportDeskRoute
  '/research': typeof ResearchRoute
  '/us-link': typeof UsLinkRoute
  '/us-research': typeof UsResearchRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/api/market-stream': typeof ApiMarketStreamRoute
  '/etfs/$code': typeof EtfsCodeRoute
  '/industry/$sectorId': typeof IndustrySectorIdRoute
  '/status/sources': typeof StatusSourcesRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/us-research/$reportId': typeof UsResearchReportIdRoute
  '/us/$symbol': typeof UsSymbolRoute
  '/etfs/': typeof EtfsIndexRoute
  '/us-research/': typeof UsResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclosures'
    | '/etfs'
    | '/export-desk'
    | '/research'
    | '/us-link'
    | '/us-research'
    | '/watchlist'
    | '/api/market-stream'
    | '/etfs/$code'
    | '/industry/$sectorId'
    | '/status/sources'
    | '/stock/$ticker'
    | '/us-research/$reportId'
    | '/us/$symbol'
    | '/etfs/'
    | '/us-research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclosures'
    | '/export-desk'
    | '/research'
    | '/us-link'
    | '/watchlist'
    | '/api/market-stream'
    | '/etfs/$code'
    | '/industry/$sectorId'
    | '/status/sources'
    | '/stock/$ticker'
    | '/us-research/$reportId'
    | '/us/$symbol'
    | '/etfs'
    | '/us-research'
  id:
    | '__root__'
    | '/'
    | '/disclosures'
    | '/etfs'
    | '/export-desk'
    | '/research'
    | '/us-link'
    | '/us-research'
    | '/watchlist'
    | '/api/market-stream'
    | '/etfs/$code'
    | '/industry/$sectorId'
    | '/status/sources'
    | '/stock/$ticker'
    | '/us-research/$reportId'
    | '/us/$symbol'
    | '/etfs/'
    | '/us-research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclosuresRoute: typeof DisclosuresRoute
  EtfsRoute: typeof EtfsRouteWithChildren
  ExportDeskRoute: typeof ExportDeskRoute
  ResearchRoute: typeof ResearchRoute
  UsLinkRoute: typeof UsLinkRoute
  UsResearchRoute: typeof UsResearchRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  ApiMarketStreamRoute: typeof ApiMarketStreamRoute
  IndustrySectorIdRoute: typeof IndustrySectorIdRoute
  StatusSourcesRoute: typeof StatusSourcesRoute
  StockTickerRoute: typeof StockTickerRoute
  UsSymbolRoute: typeof UsSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etfs': {
      id: '/etfs'
      path: '/etfs'
      fullPath: '/etfs'
      preLoaderRoute: typeof EtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-desk': {
      id: '/export-desk'
      path: '/export-desk'
      fullPath: '/export-desk'
      preLoaderRoute: typeof ExportDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-link': {
      id: '/us-link'
      path: '/us-link'
      fullPath: '/us-link'
      preLoaderRoute: typeof UsLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-research': {
      id: '/us-research'
      path: '/us-research'
      fullPath: '/us-research'
      preLoaderRoute: typeof UsResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-stream': {
      id: '/api/market-stream'
      path: '/api/market-stream'
      fullPath: '/api/market-stream'
      preLoaderRoute: typeof ApiMarketStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etfs/': {
      id: '/etfs/'
      path: '/'
      fullPath: '/etfs/'
      preLoaderRoute: typeof EtfsIndexRouteImport
      parentRoute: typeof EtfsRoute
    }
    '/etfs/$code': {
      id: '/etfs/$code'
      path: '/$code'
      fullPath: '/etfs/$code'
      preLoaderRoute: typeof EtfsCodeRouteImport
      parentRoute: typeof EtfsRoute
    }
    '/industry/$sectorId': {
      id: '/industry/$sectorId'
      path: '/industry/$sectorId'
      fullPath: '/industry/$sectorId'
      preLoaderRoute: typeof IndustrySectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/sources': {
      id: '/status/sources'
      path: '/status/sources'
      fullPath: '/status/sources'
      preLoaderRoute: typeof StatusSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$ticker': {
      id: '/stock/$ticker'
      path: '/stock/$ticker'
      fullPath: '/stock/$ticker'
      preLoaderRoute: typeof StockTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-research/': {
      id: '/us-research/'
      path: '/'
      fullPath: '/us-research/'
      preLoaderRoute: typeof UsResearchIndexRouteImport
      parentRoute: typeof UsResearchRoute
    }
    '/us-research/$reportId': {
      id: '/us-research/$reportId'
      path: '/$reportId'
      fullPath: '/us-research/$reportId'
      preLoaderRoute: typeof UsResearchReportIdRouteImport
      parentRoute: typeof UsResearchRoute
    }
    '/us/$symbol': {
      id: '/us/$symbol'
      path: '/us/$symbol'
      fullPath: '/us/$symbol'
      preLoaderRoute: typeof UsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EtfsRouteChildren {
  EtfsCodeRoute: typeof EtfsCodeRoute
  EtfsIndexRoute: typeof EtfsIndexRoute
}

const EtfsRouteChildren: EtfsRouteChildren = {
  EtfsCodeRoute: EtfsCodeRoute,
  EtfsIndexRoute: EtfsIndexRoute,
}

const EtfsRouteWithChildren = EtfsRoute._addFileChildren(EtfsRouteChildren)

interface UsResearchRouteChildren {
  UsResearchReportIdRoute: typeof UsResearchReportIdRoute
  UsResearchIndexRoute: typeof UsResearchIndexRoute
}

const UsResearchRouteChildren: UsResearchRouteChildren = {
  UsResearchReportIdRoute: UsResearchReportIdRoute,
  UsResearchIndexRoute: UsResearchIndexRoute,
}

const UsResearchRouteWithChildren = UsResearchRoute._addFileChildren(
  UsResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclosuresRoute: DisclosuresRoute,
  EtfsRoute: EtfsRouteWithChildren,
  ExportDeskRoute: ExportDeskRoute,
  ResearchRoute: ResearchRoute,
  UsLinkRoute: UsLinkRoute,
  UsResearchRoute: UsResearchRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  ApiMarketStreamRoute: ApiMarketStreamRoute,
  IndustrySectorIdRoute: IndustrySectorIdRoute,
  StatusSourcesRoute: StatusSourcesRoute,
  StockTickerRoute: StockTickerRoute,
  UsSymbolRoute: UsSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
